### ISSUE TITLE
Move Visualizer to netstandard2.0

### ISSUE THREAD

**Issue by VaclavElias** [codecapital/EnumerableVisualizer#2]
Visual Studio 2019, debugging on ASP.NET Core App 

Causes
![image](https://user-images.githubusercontent.com/4528464/59364046-24fbbb00-8d2e-11e9-8449-96f2c821321f.png)

When added System.Windows.Forms to the same folder, another error

![image](https://user-images.githubusercontent.com/4528464/59364205-5f655800-8d2e-11e9-9350-cac80c134180.png)

**Comment by VaclavElias** [comment]
Check if any implementation from here https://github.com/zspitz/ExpressionToString could be integrated.

**Comment by zspitz** [comment]
I'm not sure the visualizer itself needs to target .NET Standard. It's being loaded by Visual Studio which is still compiled under .NET Framework. My expression tree visualizer [targets .NET Framework](https://github.com/zspitz/ExpressionToString/blob/master/ExpressionTreeVisualizer.2019/Visualizer.2019.csproj) and can still visualize expression trees in .NET Core assemblies (after [this](https://github.com/zspitz/ExpressionToString/wiki/Troubleshooting-visualizer-installation)).

**Comment by VaclavElias** [comment]
@zspitz I think, it doesn't need to. I had to play like 8+ hours but your code really helped me so all is working now. Thank you for suggesting to look into your solution :).

I have added it to Core branch https://github.com/codecapital/EnumerableVisualizer/tree/core, it is a mess but it is working. You have to include all files in /Dist folder if you would like to try it.

Also, for some reason not all json stream is parsed to DataGrid, have to play with it, also I don't like the default XAML DataGrid but that's not important.

What I do is:

1. "Any" enumerable object comes to EnumerableObjectSource
1. It is serialised to JSON
1. Then to byte Stream, all nicely done through one line of JsonSerializer.ToUtf8Bytes()
1. In Visualizer, the byte Stream is received, converted to string
1. Then converted to DataTable - Here the problem is, this worked in Windows.Forms, in XAML it works partially, I have to check why it is not working fully, most likely some little thing (null), also not sure if DataTable is the best thing for DataGrid..

Then there is some work needed to make the Grid looking much better actually whole UI...

Regarding .NET Standard, they do say to use .NET Standard https://docs.microsoft.com/en-us/visualstudio/debugger/walkthrough-writing-a-visualizer-in-csharp?view=vs-2019 also there is another version of it but it doesn't have certain methods so I couldn't use it (Show(IDialogVisualizerService windowService, IVisualizerObjectProvider objectProvider)).

![image](https://user-images.githubusercontent.com/4528464/59791375-d8822380-92c9-11e9-8d17-28d68f954f34.png)

![image](https://user-images.githubusercontent.com/4528464/59792606-72e36680-92cc-11e9-9333-77fab827c726.png)


I guess, once .NET Core 3.0  and .NET Standard 2.1 is out then this will be more clear.

**Comment by VaclavElias** [comment]
Closing, this project is going to be archived as the functionality is now available directly in the Visual Studio as **IEnumerable Visualizer**.
