### ISSUE TITLE
Dictionary support

### ISSUE THREAD

**Issue by LaraSQP** [codecapital/EnumerableVisualizer#3]
First, thank you very, very much for taking the time to develop this extension and for making it available to all.

It works fantastically well for lists, hashsets, and other structures I have tried. The filter is a joy.

But, while the visualizer magnifier also shows up for dictionaries, the `VisualizerForm` pops up empty every time. No data.

Am I missing something here?

Thanks again.

**Comment by VaclavElias** [comment]
Hi @LaraSQP, you are welcome.

Actually I don't know. I have to look into it. I have got a new json flattener https://github.com/codecapital/CodeCapital.AspNetCore/tree/main/src/CodeCapital.System.Text.Json and I am planning some refactoring. Behind the scene, Visual Studio sends json which I am then flattening to the grid. I just need to see how a dictionary could fit here. I will leave this ticket open till I have got some answers 😃.

**Comment by LaraSQP** [comment]
Much appreciated.

I have been clumsily playing with the code and, once I understand it better, will try to virtualize the grid (or a listview) so that the loading process won't take as long for large structures/data.

Thanks again. Good karma to you.

**Comment by VaclavElias** [comment]
I believe, there are lots of possibilities to improve this extension from loading the data to better UI. I was using only shortcuts to get any possible happy path working for majority lists. I was also thinking using XAML and .NET MAUI but not sure about that. 

To be honest, I don't know why Microsoft hasn't done this extension already. I should ask @madskristensen to adopt this 😃.

Good karma to you too!

**Comment by VaclavElias** [comment]
@LaraSQP this is now in VS https://devblogs.microsoft.com/visualstudio/view-net-collections-with-the-new-ienumerable-debugger-visualizer/, most likely not the Dictionary support..

**Comment by LaraSQP** [comment]
Thanks. I did play with it and it was not so good. My fault, I guess.

**Comment by VaclavElias** [comment]
Closing, this project is going to be archived as the functionality is now available directly in the Visual Studio as **IEnumerable Visualizer**.
